package com.aniket.connect4blood.utils

class AppVals private constructor() {
    companion object {
        const val APP_SHARED_PREFS_NAME = "connect4blood_auth_prefs"
        const val APP_SHARED_PREFS_INIT_AUTH_KEY = "loggedInAs"
        const val APP_DEFAULT_DATETIME_FORMAT = "dd-MM-yyyy HH:mm:ss"
        const val APP_DEFAULT_MAX_SEARCH_DISTANCE = 15
        const val ARG_KEY_REQUEST_ID = "requestId"
        const val ARG_KEY_DONOR_LIST_SIZE_GET = "getDonorListSize"
        const val ARG_KEY_DONOR_LIST_SIZE = "donorListSize"
        const val ARG_KEY_CURRENT_USER = "currentUser"
        const val PROGRESS_GENERIC = "Please wait..."
        const val ERROR_EMAIL_EMPTY = "Error! Please enter the new email address!"
        const val SEND_OTP = "Sending OTP"
        const val OTP_SENT = "OTP Sent!\nReading OTP"
        const val OTP_VERIFYING = "Verifying OTP"
        const val OTP_RESEND = "Resending OTP"
        const val ERROR_INVALID_OTP = "Error! Please enter a valid OTP."
        const val ERROR_EMPTY_OTP = "Error! OTP field cannot be empty."
        const val ERROR_EMPTY_PHONE_NO = "Error! Phone no. field cannot be empty."
        const val ERROR_INVALID_PHONE_NO = "Error! Please enter a valid phone number."
        const val ERROR_TOO_MANY_REQUEST = "Error! Too many requests were initiated."
        const val ERROR_GENERIC = "Error! Something went wrong, Please try again later."
        const val ERROR_USER_COLLISION_MOBILE = "Error! This mobile no is already linked to another account."
        const val ERROR_USER_DISABLED_MOBILE = "Error! User account linked to this mobile no has been deactivated."
        const val SUCCESS_PHONE_UPDATE = "Your phone number was updated successfully!"
        const val SEND_VERIFY_EMAIL = "Email Updated Successfully\nSending Verification Email"
        const val SENT_VERIFY_EMAIL = "Verification Email Sent! Please check your inbox and click on the verification link to be able to login again."
        const val UPDATING_EMAIL = "Updating Email"
        const val ERROR_INVALID_EMAIL = "Error! Please enter a valid email address."
        const val ERROR_USER_COLLISION_EMAIL = "Error! This email address is already linked to another account."
        const val ERROR_USER_DISABLED_EMAIL = "Error! User account linked to this email address has been deactivated"
        const val ERROR_RECENT_LOGIN_REQUIRED = "Re-authentication required!"
        const val ERROR_FIELDS_EMPTY = "Error! All field are mandatory, make sure they are not empty."
        const val ERROR_PASS_FIELDS_NOT_EQUAL = "Error! New Password and Confirm Password fields should contain the same password."
        const val SUCCESS_PASS_UPDATE = "Password updated successfully! Please login again."
        const val SUCCESS_ACCOUNT_CLOSURE = "Your account was closed successfully!"
        const val ERROR_PASSWORD = "Error! Password entered is invalid."
        const val ERROR_EMPTY_CUR_PASS = "Error! Please enter the current password."
        const val CREATE_SUPPORT_TICKET = "Generating\nSupport Ticket"
        const val SUCCESS_SUPPORT_TICKET_GENERATED = "Ticket Generated! Your message was sent to our support team."
        const val ERROR_TOO_MANY_BACKEND_REQUESTS = "Error! Too many requests were initiated."
        const val ERROR_USER_NOT_REGISTERED = "Error! No user account was found linked to this phone number."
        const val ERROR_ACCEPT_TERMS = "Error! Please accept the terms to continue."
    }
}